# Generated by Django 3.2.3 on 2021-05-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('Volume', (('cup', 'cups'), ('tbsp', 'tbsp'), ('tsp', 'tsp'))), ('Weight', (('lb', 'pounds'),))], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
    ]
