# Generated by Django 3.2.3 on 2021-05-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210519_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
